### ISSUE TITLE
InterpolatedSymbolNode even when not interpolated

### ISSUE THREAD

**Issue by eregon** [ruby/yarp#1120]
```
$ bin/parse -e ':"foobar"'
#<YARP::ParseResult:0x00007f44a7833ef0
 @comments=[],
 @errors=[],
 @value=
  ProgramNode(0...9)(
    [],
    StatementsNode(0...9)(
      [InterpolatedSymbolNode(0...9)((0...2), [StringNode(2...8)(nil, (2...8), nil, "foobar")], (8...9))]
    )
  ),
 @warnings=[]>
```

But there is no actual interpolation here, it's just a Symbol literal using `"`.
Currently we're working around by detecting the pattern in TruffleRuby, but I think this should just be a SymbolNode.

**Comment by tenderlove** [comment]
I'm not sure if we'd want to do that.  First, I think changing to just a SymbolNode would mean that the AST loses some information (the fact that the string was surrounded by double quotes), and second it feels weird to special case this.  IOW, I'm not sure why `:"foobar"` shouldn't be considered interpolated when `:"foo#{x}bar"` definitely is.

It seems like detecting this pattern in the compiler is the right thing to do.

**Comment by eregon** [comment]
> I'm not sure why `:"foobar"` shouldn't be considered interpolated when `:"foo#{x}bar"` definitely is.

My understanding/definition of *interpolated* is it interpolates something, i.e., it uses `#{}` (or `#@foo/#$foo`).
The `"` are just useful e.g. if you want spaces, `:"a b"`, I think nobody would think `"a b"` as interpolated.
(using "" instead of ''/nothing does allow for interpolation, but if no `#` is used it's not interpolated)

Compare:
```
$ bin/parse -e '"a b"'
#<YARP::ParseResult:0x00007fa6c6503fd8
 @comments=[],
 @errors=[],
 @value=ProgramNode(0...5)([], StatementsNode(0...5)([StringNode(0...5)((0...1), (1...4), (4...5), "a b")])),
 @warnings=[]>

$ bin/parse -e ':"a b"'
#<YARP::ParseResult:0x00007fa07c013f28
 @comments=[],
 @errors=[],
 @value=
  ProgramNode(0...6)(
    [],
    StatementsNode(0...6)([InterpolatedSymbolNode(0...6)((0...2), [StringNode(2...5)(nil, (2...5), nil, "a b")], (5...6))])
  ),
 @warnings=[]>
```

**Comment by eregon** [comment]
> I think changing to just a SymbolNode would mean that the AST loses some information (the fact that the string was surrounded by double quotes)

That can be tracked by opening_loc/closing_loc I believe:
```yaml
  - name: SymbolNode
    child_nodes:
      - name: opening_loc
        type: location?
      - name: value_loc
        type: location
      - name: closing_loc
        type: location?
      - name: unescaped
        type: string
    comment: |
      Represents a symbol literal or a symbol contained within a `%i` list.

          :foo
          ^^^^

          %i[foo]
             ^^^
```
