### ISSUE TITLE
ParenthesesNode#statements

### ISSUE THREAD

**Issue by eregon** [ruby/yarp#1121]
Should it be named `statement` or `body` or so since it's a single optional node:
```yaml
  - name: ParenthesesNode
    child_nodes:
      - name: statements
        type: node?
      - name: opening_loc
        type: location
      - name: closing_loc
        type: location
    comment: |
      Represents a parentesized expression

          (10 + 34)
          ^^^^^^^^^
```

Example:
```
$ bin/parse -e '(true) ? 42 : 100500'
#<YARP::ParseResult:0x00007fcc27083db0
 @comments=[],
 @errors=[],
 @value=
  ProgramNode(0...20)(
    [],
    StatementsNode(0...20)(
      [IfNode(0...20)(
         nil,
         ParenthesesNode(0...6)(StatementsNode(1...5)([TrueNode(1...5)()]), (0...1), (5...6)),
         StatementsNode(9...11)([IntegerNode(9...11)()]),
         ElseNode(12...20)((12...13), StatementsNode(14...20)([IntegerNode(14...20)()]), nil),
         nil
       )]
    )
  ),
 @warnings=[]>
```

BTW we don't need that node for semantics (easy to ignore it), OTOH I guess it's very useful for syntax tools.
