### ISSUE TITLE
The `exception` and `exceptions` fields in `RescueNode` are confusing a bit

### ISSUE THREAD

**Issue by andrykonchin** [ruby/yarp#1160]
`RescueNode` represents a `rescue` section and has `exception` and `exceptions` fields for optional exception classes
 and optional exception variable:

```
...
rescue <exceptions> => <exception>
```

These names look a bit confusing - it might be not obvious for someone what exactly they mean and it will be helpful to make them more precise.

Not sure if there are common used terms for these things. I could propose the following alternatives only:

### `exceptions`:
- exception classes (but it might be not only classes but some expression, e.g. `*exceptions_array`)
- exceptions list
- rescued exceptions
- expected exceptions

### `exception`:
- exception variable (but it might be also constant or method call (`a.foo` or `a[:foo]`))
- just "assignable" as far as semantic is to assign exception to the provided name

### Declaration of the `RescueNode` node:

```yaml
  - name: RescueNode
    child_nodes:
      - name: keyword_loc
        type: location
      - name: exceptions
        type: node[]
      - name: operator_loc
        type: location?
      - name: exception
        type: node?
      - name: statements
        type: node?
        kind: StatementsNode
      - name: consequent
        type: node?
        kind: RescueNode
```
